language: java

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - mvn install

after_script:
# Upload code coverage to code climate - with workaround for jacoco
  - cp target/site/jacoco/jacoco.xml src/main/java/jacoco.xml
  - cd src/main/java/
  - ../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
