language: java

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - mvn install

JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter \
  format-coverage target/site/jacoco/jacoco.xml     \
  --input-type jacoco
./cc-test-reporter upload-coverage
